### ISSUE TITLE
Some questions about Quantitative Evaluation

### ISSUE THREAD

**Issue by Gloria-coder** [xupei0610/KDMA#10]
Hi. I have read your paper. You do a very good job!
I want to know that if there are some codes about the ORCA and RL you have used to do comparisons to KDMA. I have some questions about the parameters.

**Comment by xupei0610** [comment]
The performance of ORCA depends a lot on the choice of parameters. We use https://github.com/sybrenstuvel/Python-RVO2 for ORCA agent control. The parameters are listed below:

neighborDist: 5 (same with our KDMA agent settings)
maxNeighbors: 50
timeHorizon: 10
timeHorizonObst: 10 (useless, as there is no obstacles in our testing scenarios)
radius: 0.12 (a 0.02 tolerance is introduced, while the radius settings for KDMA training is 0.1)
maxSpeed: 2.5 (same with KDMA settings)
prefVelocity: goal-directed with a preferred speed of 1.3 (same with KDMA settings)

The RL settings are the same as KDMA but without the expert term in the reward function.

**Comment by Gloria-coder** [comment]
Thank you for your reply!
