### ISSUE TITLE
Can I directly train the policy without training the expert?

### ISSUE THREAD

**Issue by chenzhutian** [xupei0610/KDMA#3]
Thanks for your great repo.
I am wondering whether it is possible to train the policy directly without training the expert?

Thanks!

**Comment by xupei0610** [comment]
Our approach generates human-like navigation trajectories relying on knowledge distillation from the expert policy. Therefore, the expert policy is a necessary part to reproduce the results shown in our paper.

To train a normal multi-agent navigation policy without knowledge distillation, you have to modify the file train_poliy.py to initialize the training without loading the expert policy. For better training results, probably, you also have to change the reward function defined in models/env.py.
