### ISSUE TITLE
Why there are 4 zeros in the agent's observed state?

### ISSUE THREAD

**Issue by chenzhutian** [xupei0610/KDMA#4]
Thanks again for your repo : )
So in the `observe` function, I find that the state include 4 `0.`: https://github.com/xupei0610/KDMA/blob/main/models/agent.py#L52

But I think in the paper you mentioned that there is only one dummy representation for the agent it self
![image](https://user-images.githubusercontent.com/3315274/149885076-b30270e7-51e7-4446-b2c7-3e6271cc9660.png)

So I wonder why there is four `0.` instead of two?

**Comment by xupei0610** [comment]
The dummy neighbor representation is a 4-dimension vector, which is the same as the general neighbor representation o_{i,t}^{n_j}. The two **0** are actually two 2-dimension vectors corresponding to $p_{j,t} - p_{i,t}$ and $v_{j,t} - v_{i,t}$ in $o_{i,t}^{n_j}$ respectively.

**Comment by chenzhutian** [comment]
OH I see. Thanks!
