### ISSUE TITLE
Is the distributed training code incorrect?

### ISSUE THREAD

**Issue by chenzhutian** [xupei0610/KDMA#7]
Hi, based on the code in these lines: https://github.com/xupei0610/KDMA/blob/main/train_policy.py#L224-L233,
the `process` list always have one process, i.e., the one with rank 0. 
Is this incorrect? Oh do I miss something?
thanks!

**Comment by chenzhutian** [comment]
BTW, right now I run the command eight times on the same machine:
`python train_policy.py --rank 0 --workers 8 --device cuda:0 --expert <expert_log_dir> --log_dir <policy_log_dir> &`

**Comment by xupei0610** [comment]
The code is correct.

Each `python train_policy.py` will open a training process. But, for the chief trainer (rank = 0), it will open a subprocess to do the training, while the main process  performs evaluation during training.

So, you need to run `python train_policy.py` multiple times for distributed training.  The code also supports distributed training on different machines by specifying `--master_addr` and `--master_port` arguments.

**Comment by chenzhutian** [comment]
I see. So the chief trainer only monitors whether his own subprocess is alive? because there is only one subprocesses in the child_processes array
```
  if child_processes:
      finished = not all(p.is_alive() for p in child_processes)
```
at https://github.com/xupei0610/KDMA/blob/main/train_policy.py#L153

**Comment by xupei0610** [comment]
All trainer processes (main or sub processes) will terminate automatically if the maximal number of training samples or iterations (shared among all processes) is reached. (See `job_is_done()` function in `rl/actor_critic.py`.) And, all other trainer will shutdown if the connection between them is timeout, which means that if one trainer is broken by some reasons, the other trainers will terminate as well. So the evaluator process does not need to monitor all trainers but just the chief one. Besides, it is also not easy for the evaluator process to monitor trainers running on different machines.

**Comment by chenzhutian** [comment]
Thanks! Just curious, do you use SLURM?

**Comment by xupei0610** [comment]
I have not used that. The cluster of our university uses PBS. In PBS, nothing needs to do if all trainers run on the same node, just like running things on a local machine. If trainers are run on different node, just pass `--master_addr` argument using the node name of the chief trainer process for all non-chief trainers.

**Comment by chenzhutian** [comment]
Oh great! Thanks for your information. I am managing to run the code on SLURM.
