### ISSUE TITLE
Nothing shows up when run the visualization code

### ISSUE THREAD

**Issue by chenzhutian** [xupei0610/KDMA#8]
I try to visualize the policy I leanred by using `python visualize.py --ckpt output/ckpt` 
However , if I add a break point to the code, it shows the visualization.

**Comment by xupei0610** [comment]
Have you given the `--scene` argument?

**Comment by chenzhutian** [comment]
I use the default scene "6-circle"
The program is running. it just not shows up the plt

**Comment by chenzhutian** [comment]
And I can see the visualization if I add a breakpoint in vscode

**Comment by xupei0610** [comment]
Can you visualize the provided pretrained policy?

**Comment by chenzhutian** [comment]
Noops.
![image](https://user-images.githubusercontent.com/3315274/150434326-abe655ef-f443-45ec-acae-f9c9920c3639.png)
This shows up but not response.
![image](https://user-images.githubusercontent.com/3315274/150434366-bc6a9c48-1d78-4b0e-88c4-2ac54f8ae1fb.png)

**Comment by xupei0610** [comment]
I guess it may be some version problems of matplotlib. There is no problem for me to visualize things on my machine. Probably, you can try adding `plt.pause(0.0001)` at the very end of `env/multi_agent_env.py` inside `render()` function after calling `fig.canvas.draw()`.

**Comment by chenzhutian** [comment]
amazing after adding `plt.pause(0.0001)` it works! 
Thanks!
