### ISSUE TITLE
where is the code to draw the value heatmap?

### ISSUE THREAD

**Issue by chenzhutian** [xupei0610/KDMA#9]
Hi, thanks for the great repo, again!
May I ask where is the code to draw the value heatmap?
Thanks!

**Comment by xupei0610** [comment]
We did not provide the code to draw the heatmap, as it needs some tricks and manual work to visualize the heatmap. The heatmap is a state-action-value (or say Q value) map, but our approach using PPO works only relying on the state value. To draw the heatmap, we can estimate the Q value by `r(s_t, a_t, s_{t+1}) + gamma*V(s_{t+1})` given the state `s_t`, action `a_t` , the state at next time step `s_{t+1}` and `V(s_{t+1})` from the value network. So, we need to enumerate `a_t` manually using discretized values across the whole action space.

**Comment by chenzhutian** [comment]
wondering why we need `s_{t+1}` for `r`?

**Comment by xupei0610** [comment]
`s_{t+1}` is unnecessary if the computation of reward does not need information from `s_{t+1}`. 

In our approach, we need `s_{t+1}` to decide if the agent reaches the goal or collide after taking the action `a_{t}`.

**Comment by chenzhutian** [comment]
so is it something like
```
foreach agent:
   apply(a_t, s_t)

foreach agent:
   calculate_reward(s_{t+1})
```

**Comment by xupei0610** [comment]
`reward` is to evaluate how good/bad it is to take an action at a given state. So, the general form of reward computation is a function involving the current (given) state, the action, and the resulting state. That is `r(s_t, a_t, s_{t+1})`. 

Of course, the computation of reward is completely dependent on how you define it. That is to say, in practice, you can use anything, which may or may not include `s_t`, `a_t` and `s_{t+1}`, to compute the reward.
